global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['frontend:8080']

  - job_name: 'microusers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['microusers:8081']
