version: "3.8"

services:

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile    
      ports:
        - "8080:8080"
      networks:
        - clase
          
    micrusers:
      build: 
        context: ./microusers
        dockerfile: Dockerfile   
      ports:
        - "8081:8081"
      networks:
        - clase
networks:
  clase:
