apiVersion: apps/v1
kind: Deployment
metadata:
  name: microusers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microusers
  template:
    metadata:
      labels:
        app: microusers
    spec:
      containers:
      - name: microusers
        image: juankmore/microusers:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: microusers-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: microusers
