apiVersion: apps/v1
kind: Deployment
metadata:
  name: microusers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microusers
  template:
    metadata:
      labels:
        app: microusers
    spec:
      containers:
      - name: microusers
        image: jpeca79/microusers:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: microusers
spec:
  type: NodePort
  selector:
    app: microusers
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001  # Puedes ajustar este puerto si es necesario

