apiVersion: apps/v1
kind: Deployment
metadata:
  name: microusers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microusers
  template:
    metadata:
      labels:
        app: microusers
    spec:
      containers:
      - name: microusers
        image: microusers
        ports:
        - containerPort: 8081

apiVersion: v1
kind: Service
metadata:
  name: microusers-service
spec:
  selector:
    app: microusers
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
